### ISSUE TITLE
Push latest version to npm

### ISSUE THREAD

**Issue by AuspeXeu** [haraka/haraka-plugin-recipient-routes#15]

**Comment by msimerson** [comment]
If you'd like a faster release, please create a PR that updates the Changes.md and the version in package.json. Then I'll merge it and publish to npm.

**Comment by AuspeXeu** [comment]
The version in the package.json is already newer than the one on npm.org which is why I thought only a npm publish is missing :)

**Comment by msimerson** [comment]
Well why didn't you just say that? ;-)

````
$ npm publish
+ haraka-plugin-recipient-routes@1.0.2
````
