### ISSUE TITLE
Redis functionality doesnt appear to ever trigger

### ISSUE THREAD

**Issue by ainesophaur** [haraka/haraka-plugin-recipient-routes#23]
Line 108 of [index.js](https://github.com/haraka/haraka-plugin-recipient-routes/blob/master/index.js#L108) seems to prevent redis based functionality. Im assuming its likely an oversight from transitioning to redis v4. Based on `haraka-plugin-redis` this.redis_pings gets set by calling `await this.redis_ping()` which seems to only be called in tests within this project.

**Comment by msimerson** [comment]
I just released a 1.0.4 that should address this.

**Comment by ainesophaur** [comment]
Unfortunately, for me v1.0.4 introduces the following error

```
[CRIT] [-] [core] Error: redis not initialized
[CRIT] [-] [core]     at exports.redis_ping (/Users/user/Projects/xd/github/inbox/mailers/inbound/node_modules/haraka-plugin-redis/index.js:148:25)
[CRIT] [-] [core]     at exports.register (/Users/user/Projects/xd/github/inbox/mailers/inbound/node_modules/haraka-plugin-recipient-routes/index.js:16:8)
[CRIT] [-] [core]     at plugins._register_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:404:12)
[CRIT] [-] [core]     at plugins.load_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:378:17)
```

I created a local fork of the repo which resolved the original issue by calling `redis_ping()` outside of the registration (as I had the same issue as above when calling redis_ping from registration)

Below is a snippet of the rcpt hook

```javascript
if (!!this.db && ! await this.redis_ping() ) {
    return next(await this.do_file_search(txn, address, domain));
 }
```

I can submit a PR or attach a patch if that would help.

**Comment by msimerson** [comment]
Oh dang, a race issue. Yes, please submit a PR.

**Comment by msimerson** [comment]
Upon further review, the reason redis_ping() failed in `register` is because it was called *before* init_redis_plugin.
